config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  resources :tasks
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :blogs do
    resources :comments
    
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resources :tasks
    resources :submit_requests , shallow: true do
      get 'approve'
      get 'unapprove'
      get 'reject'
      collection do
        get 'inbox'
      end
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  root 'top#index'
  

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = Notification.where(user_id: current_user.id).where(read: false).order(created_at: :desc)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def posted_time(time)
    time > Date.today ? "#{time_ago_in_words(time)}" : time.strftime('%m月%d日')
  end
  def read_display_name(read)
    read ? '既読' : '未読'
  end
end

app/views/notifications/index.html.erb
<h2>お知らせ</h2>
<ul>
  <% @notifications.each do |notification| %>
  <hr>
    <li>
      <span><%= read_display_name(notification.read) %></span>
      <p>
        <%= notification.comment.user.try(:name) %>さんが
        あなたのブログ（<%= link_to "#{notification.comment.blog.title}", blog_path(notification.comment.blog, notification_id: notification.id) %>）にコメントしました。
      </p>
      <p><%= notification.created_at %></p>
    </li>
  <% end %>
</ul>